import streamlit as st

from api_client import list_reports, report_download_url
from theme import badge, hero, inject_theme

st.set_page_config(page_title="Reports - rag-chat", page_icon="🧾", layout="wide")
inject_theme()
hero("🧾 Reports", "Reports generated by the chat agent (CSV/Excel) are listed here for download.")

if st.button("Refresh"):
    st.rerun()

try:
    data = list_reports(limit=200)
except Exception as exc:
    st.error(f"Could not load reports: {exc}")
    data = {"items": []}

if not data["items"]:
    st.write("No reports generated yet. Ask the chat agent to generate one, e.g. "
             "\"Generate a report of document counts by classification\".")
else:
    for r in data["items"]:
        with st.container(border=True):
            col1, col2 = st.columns([4, 1])
            with col1:
                st.markdown(f"**{r['title']}** {badge(r['format'])}", unsafe_allow_html=True)
                st.caption(f"{r['row_count']} rows · {r['created_at']}")
            with col2:
                st.link_button("Download", report_download_url(r["id"]))
