import streamlit as st

import api_client
from api_client import APIError
from components import card, debug_json, page_header, show_api_error

page_header("Reports", "bar_chart", "Files generated by the chat agent's `generate_report` tool.", color="orange-70")

try:
    result = api_client.list_reports(limit=50)
except APIError as exc:
    show_api_error(exc)
    st.stop()

if not result["items"]:
    st.info("No reports yet — ask the chat assistant to generate one.")
else:
    for report in result["items"]:
        with card(f"report_card_{report['id']}"):
            c1, c2 = st.columns([4, 1])
            c1.markdown(f"**{report['title']}** ({report['format']}, {report['row_count']} rows)")
            c1.caption(report["created_at"])

            # The report file lives on the backend's filesystem, not the
            # browser's — Streamlit fetches the bytes server-side (via
            # api_client) and then re-serves them to the browser, rather than
            # linking straight to a backend URL the browser may not reach.
            if c2.button("Fetch", key=f"fetch_{report['id']}"):
                try:
                    content, content_type, filename = api_client.download_report(report["id"])
                except APIError as exc:
                    show_api_error(exc)
                else:
                    st.download_button(
                        "⬇️ Download", data=content, file_name=filename, mime=content_type,
                        key=f"dl_{report['id']}",
                    )

    debug_json(result, "Raw /reports response")
